# Generated by Django 3.2.25 on 2025-01-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='CPU名称')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('score', models.CharField(max_length=50, verbose_name='评分')),
                ('comments', models.CharField(max_length=50, verbose_name='评论数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='品牌')),
                ('series', models.CharField(blank=True, max_length=50, verbose_name='系列')),
            ],
            options={
                'verbose_name': 'CPU',
                'verbose_name_plural': 'CPU列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GraphicsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='显卡名称')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('score', models.CharField(max_length=50, verbose_name='评分')),
                ('comments', models.CharField(max_length=50, verbose_name='评论数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='品牌')),
                ('memory_size', models.CharField(blank=True, max_length=50, verbose_name='显存大小')),
            ],
            options={
                'verbose_name': '显卡',
                'verbose_name_plural': '显卡列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HardDisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='硬盘名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('specifications', models.TextField(blank=True, verbose_name='规格')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('score', models.CharField(max_length=50, verbose_name='评分')),
                ('comments', models.CharField(max_length=50, verbose_name='评论数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
            ],
            options={
                'verbose_name': '硬盘',
                'verbose_name_plural': '硬盘列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='内存名称')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('score', models.CharField(max_length=50, verbose_name='评分')),
                ('comments', models.CharField(max_length=50, verbose_name='评论数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
                ('capacity', models.CharField(blank=True, max_length=50, verbose_name='容量')),
                ('frequency', models.CharField(blank=True, max_length=50, verbose_name='频率')),
            ],
            options={
                'verbose_name': '内存',
                'verbose_name_plural': '内存列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='主板名称')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('score', models.CharField(max_length=50, verbose_name='评分')),
                ('comments', models.CharField(max_length=50, verbose_name='评论数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='品牌')),
                ('chipset', models.CharField(blank=True, max_length=50, verbose_name='芯片组')),
            ],
            options={
                'verbose_name': '主板',
                'verbose_name_plural': '主板列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='电源名称')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('score', models.CharField(max_length=50, verbose_name='评分')),
                ('comments', models.CharField(max_length=50, verbose_name='评论数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
            ],
            options={
                'verbose_name': '电源',
                'verbose_name_plural': '电源列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
